###
POST http://localhost:3000/api/productos HTTP/1.1
Content-Type: application/json

{
    "name":"guitarra",
    "categoria":"Instrumento",
    "price": 20000,
    "stock": 5
}

###
GET http://localhost:3000/api/productos HTTP/1.1

###
GET http://localhost:3000/api/productos/6478ebafa358992bae5cac50 HTTP/1.1

###
PUT http://localhost:3000/api/productos/6478ebafa358992bae5cac50 HTTP/1.1
Content-Type: application/json

{
    "name":"arpa",
    "categoria":"Instrumento",
    "price": 20000,
    "stock": 6
}

###
DELETE http://localhost:3000/api/productos/6478e85038b24f1bbdf728cc HTTP/1.1